learning_rate: 0.001 # The only problem right now is that 1e-3 would be converted to str type
batch_size: 32
num_epochs: 25

cnn:
  num_layers: 3
  layer_init:
    type: 'normal'
    mean: 0
    std: 0.1

resnet:
  model_type: 'resnet18'